<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Persistence\Services\**" />
    <EmbeddedResource Remove="Persistence\Services\**" />
    <MauiCss Remove="Persistence\Services\**" />
    <MauiXaml Remove="Persistence\Services\**" />
    <None Remove="Persistence\Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\KoreanLearningApp.Domain.csproj" />
    <ProjectReference Include="..\KoreanLearningApp.Services\KoreanLearningApp.Services.csproj" />
  </ItemGroup>

</Project>
